from registry.cn-beijing.aliyuncs.com/hub-mirrors/openjdk:11

COPY target/dreamone-customer-system.jar /root/dreamone-customer-system.jar

ENTRYPOINT ["java","-jar","/root/dreamone-customer-system.jar"]