apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamone-customer-system-deployment
  labels:
    run: dreamone-customer-system
    name: dreamone-customer-system
spec:
  imagePullSecrets:
    - name: acr-credential-dreamone-customer-system
  replicas: 1
  selector:
    matchLabels:
      run: dreamone-customer-system
  template:
    metadata:
      labels:
        run: dreamone-customer-system
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "dreamone-customer-system"
    spec:
      containers:
      - image: ${IMAGE}
        name: app
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                key: SPRING_DATASOURCE_URL
                name: dreamone-business-system-credentials
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                key: SPRING_DATASOURCE_USERNAME
                name: dreamone-business-system-credentials
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SPRING_DATASOURCE_PASSWORD
                name: dreamone-business-system-credentials
          - name: DREAMONE_LOGIN_USER
            valueFrom:
              secretKeyRef:
                key: DREAMONE_LOGIN_USER
                name: dreamone-business-system-credentials