apiVersion: v1
kind: Service
metadata:
  name: dreamone-business-system
  namespace: default
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  selector:
    run: dreamone-business-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: normal
    - protocol: TCP
      port: 8091
      targetPort: 8091
      name: metrics